### ISSUE TITLE
Addon distribution 

### ISSUE THREAD

**Issue by kriberg** [lukeknxt/classicwow-to-guidelime#67]
Hey, have the classicwow authors said anything about distributing the guides on of the addon sites? Can we package them and upload somewhere for convenience? I see they've removed the guides now and redirects to wow tavern instead, so possibly it would be more kosher now.

**Comment by lukeknxt** [comment]
Hey @kriberg ! I'm not sure whether the ones on Warcraft Tavern are the same guides ported over there, or whether Warcraft Tavern offered levelling guides prior. I haven't been in touch with them for a long time, so I can't say for sure or speak on their behalf unfortunately. You might be able to reach out to them via their Reddit accounts.
